### ISSUE TITLE
Use mousewheel to increase/decrease values

### ISSUE THREAD

**Issue by guillaumecardon** [Basssiiie/OpenRCT2-RideVehicleEditor#111]
**Idea**
Use mousewheel to increase/decrease values

**Additional context**
Like others tools in OpenRC2, you can use your mousewheel to increase/decrease value.

**Comment by Manticore-007** [comment]
I'm not even sure if that's possible for plugins, I think it should be posted at the OpenRCT2 repository

**Comment by Basssiiie** [comment]
Unless other plugins have the this functionality, I also think it's something that may require modifications to OpenRCT2 itself instead of this plugin.

**Comment by Basssiiie** [comment]
It's been a while, but it's possible [this PR](https://github.com/OpenRCT2/OpenRCT2/pull/22060) will finally fix this issue. 😄
