### ISSUE TITLE
Multiplayer doesn't work on headless servers

### ISSUE THREAD

**Issue by fidwell** [Basssiiie/OpenRCT2-RideVehicleEditor#112]
I am running a headless server (with a Docker container). I installed the plugin in my server's plugin directory. On startup, I get the following in my server logs:

```
[RideVehicleEditor] Registered
[RideVehicleEditor] Loaded
[RideVehicleEditor] Started
'UI unavailable, plugin disabled.'
```

So the plugin is getting properly loaded, starts up, but then realizes it's running in a headless server, and shuts off. If the clients have the plugin installed locally, it'll show up in the UI, but nothing will happen why they try to use it.

**Comment by Basssiiie** [comment]
Ah fair! Thanks for reporting, this is from the legacy days where multiplayer wasn't supported. 😅
